name: swap_shelf
description: A book swapping application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  url_launcher: ^6.2.2
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  path_provider: ^2.1.1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Roboto_Regular.ttf
        - asset: assets/fonts/Roboto_Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto_Bold.ttf
          weight: 700