name: swap_shelf
description: A Flutter application for book swapping

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^1.0.2
  path_provider: ^2.1.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  url_launcher: ^6.1.12
  provider: ^6.0.5  # For your AuthProvider and BookProvider

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/